---
title: "EDUC 643 Assignments"
site: distill::distill_website
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    theme: cosmo

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. General Guidelines

The goal of the assignments is to practice the concepts and vocabulary we have been modeling in class and implement some of the techniques we have learned. You may work on your own or collaborate with one (1) partner. Please make sure that you engage in a a full, fair and mutually-agreeable collaboration if you do choose to collaborate. If you do collaborate, you should plan, execute and write-up your analyses together, not simply divide the work. Please make sure to indicate clearly when your work is joint and any other individual or resource (outside of class material) you consulted in your responses.

(Here we need to add more details about global expectations and requirements for all the assignments, grading and points distribution for participation, five assignments, and/or final project/exam, late submission policy, etc. from syllabus.)

### 2. Submission Requirements

Please upload below two files on Canvas before TBD time:  

 * An .html or .pdf file that includes both - 
   + your typed responses (in your own words and not identical to anybody else's), tables, and/or figures to the problems  
   + and the R code chunks that generated your answers (hint: if you choose to compose your answers in markdown, simply set up echo = TRUE, include = TRUE in you .Rmd file)  
   
 * The .Rmd or .R file that you used to render the tables and figures in the above html/pdf. 

### 3. Details about Assignments

#### 3.1. Assignment 1

#### 3.2. Assignment 2

#### 3.3. Assignment 3

#### 3.4. Assignment 4

#### 3.5. Assignment 5

#### 3.6. Final Project

### 4. Data Sets

#### 4.1. Teacher Professional Development Study (PDS) 

The data set we'll be using in assignments 1-5 was drawn from the NCRECE [Teacher Professional Development Study (PDS)](https://www.icpsr.umich.edu/web/ICPSR/studies/34848) data. This study was a randomized controlled evaluation of two forms of professional development (PD) - coursework (phase 1) and consultancy (phase 2) - delivered to about 490 early childhood education teachers across the nation. These PD supports aimed to improve teachers' implementation of language/literacy activities and interactions with children, as well as promote gains in children's social and academic development. 

**Analytic Sample**. Our data set is student-level data for 440 preschool students. Since PDS student outcome data has not been collected during phase 1, we focus on phase 2 intervention. Specifically, the sample students were in phase 1 treatment group and in either the treatment or control group during phase 2. Observations with missing values on any of the key variables were deleted for simplification reasons.

**Key variables**. The data set contains 11 variables, detailed below.

 * *childid*, unique identification number for the student
 * *tchid*, unique identification number for the student's teacher
 * *schid*, unique identification number for the student's school
 * *cohort*, coded 1 for cohort 1 students (who started the experiment in spring 08) and 2 for cohort 2 students (who started the experiment in spring 09)
 * *treat*, coded 1 for students in phase 2 treatment group and 0 for those in phase 2 control group
 * *vocabulary*, the student's post phase 2 score on a receptive vocabulary test (Peabody Picture Vocabulary Test-3rd edition) 
 * *female*, coded 1 for female students and 0 for male students
 * *language_eng*, coded 1 for students whose primary language is English and 0 otherwise
 * *disability*, coded 1 for students with a disability and 0 otherwise
 * *ethnicity*, eight-category variable documenting the student's ethnicity
 * *mother_edu*, the student's mother's total years of education
 
**Download the [pd_stu.csv data set](./data/pd_stu.csv)**

#### 4.2. Stanford Education Data Archive (SEDA)

The data set we'll be using in our final project was drawn from the Stanford Education Data Archive ([SEDA](https://edopportunity.org)) version 4.1. SEDA was launched in 2016 to provide nationally comparable, publicly available test score data for U.S. public school districts, allowing scientific inquiries on the relationships between educational conditions, contexts, and outcomes (especially student math/ELA achievements) at the district-level across the nation. It contains rich variables including measures of academic achievement and achievement gaps for school districts and counties, as well as district-level measures of racial and socioeconomic composition, racial and socioeconomic segregation patterns, and other features of the schooling system. Some descriptive findings can be found [here](https://edopportunity.org/discoveries/).

**Analytic Sample**. Due to the large size of SEDA full data set, we focus on the school year 2017-18 data for the state of Oregon. Specifically, our data set is district-level data for 103 Oregon school districts. Observations with missing values on any of the key variables were deleted for simplification reasons.

**Key variables**. The data set contains 13 variables, detailed below.

 * *district*, name of the district
 * *subject*, coded "mth" fo Mathematics and "rla" for English/Language Arts
 * *grade*, coded 3, 4, 5, 6 for grades 3-6
 * *achievement*, grade-level average achievement test score 
 * *gap_gender*, grade-level male-female gender gap on achievement test 
 * *percent_ell*, district-level percentage of ELL students
 * *percent_sped*, district-level percentage of students in special education program
 * *percent_frl*, district-level percentage of students eligible for free or reduced school lunch
 * *percent_native*, district-level percentage of Native American students
 * *percent_asian*, district-level percentage of Asian students
 * *percent_hispanic*, district-level percentage of Hispanic students
 * *percent_black*, district-level percentage of African American students
 * *percent_white*, district-level percentage of white students
 
**Download the [seda_or.csv data set](./data/seda_or.csv)**

